language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-24
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services
    - sys-img-armeabi-v7a-addon-google_apis-google-23

env:
  - JOB=UNIT
  - JOB=COVERAGE
  - JOB=CHECKSTYLE
  - JOB=SCREENSHOT

before_script:
  - ./scripts/travis/travis-before.sh $JOB

script:
  - ./scripts/travis/travis-worker.sh $JOB

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

notifications:
  slack: the-blue-alliance:m2F6L0FT1ORBmSzKdLvAEmm1
  email: false
