sudo: required

services:
 - docker

env:
  - JOB=UNIT
  - JOB=COVERAGE
  - JOB=CHECKSTYLE

before_install:
  - docker pull neroinc/fedora-android

before_script:
  - mkdir android/src/main/assets
  - touch android/src/main/assets/tba.properties

script:
  - docker run -it -v ./:/src:z docker.io/neroinc/fedora-android /bin/bash -c "cd /src && ./scripts/travis-worker.sh $JOB"

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

notifications:
  slack: the-blue-alliance:m2F6L0FT1ORBmSzKdLvAEmm1
  email: false
