sudo: true

services:
  - docker

before_install:
  - docker pull thebluealliance/android-ci
  - docker run --name ci -v $HOME:$HOME -w `pwd` -t thebluealliance/android-ci

env:
  - JOB=UNIT
  - JOB=COVERAGE
  - JOB=CHECKSTYLE

before_script:
  - docker exec -d ci cd /opt/the-blue-alliance-android

script:
  - docker exec -d ci ./scripts/travis-worker.sh $JOB
  - docker logs ci

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

notifications:
  slack: the-blue-alliance:m2F6L0FT1ORBmSzKdLvAEmm1
  email: false
